services:
  postgres:
    image: postgres:18
    container_name: securevault-db
    restart: unless-stopped

    environment:
      POSTGRES_USER: securevault
      POSTGRES_PASSWORD: securevault_dev_password
      POSTGRES_DB: securevault

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql

  redis:
    image: redis:7-alpine
    container_name: securevault-redis
    restart: unless-stopped

    ports:
      - "6379:6379"

    command: redis-server --appendonly yes --maxmemory-policy noeviction

    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: