export const AUDIT_ACTIONS = Object.freeze({
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGOUT: 'LOGOUT',
  REFRESH_TOKEN_REUSE: 'REFRESH_TOKEN_REUSE',

  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  USER_DEACTIVATED: 'USER_DEACTIVATED',
  USER_ACTIVATED: 'USER_ACTIVATED',
  ROLE_ASSIGNED: 'ROLE_ASSIGNED',

  DOCUMENT_CREATED: 'DOCUMENT_CREATED',
  DOCUMENT_VIEW: 'DOCUMENT_VIEW',
  DOCUMENT_DOWNLOAD: 'DOCUMENT_DOWNLOAD',
  DOCUMENT_UPDATED: 'DOCUMENT_UPDATED',
  DOCUMENT_DEACTIVATED:'DOCUMENT_DEACTIVATED',
  DOCUMENT_ACTIVATED:'DOCUMENT_ACTIVATED',
  DOCUMENT_ACCESS_UPDATED: 'DOCUMENT_ACCESS_UPDATED',
  DOCUMENT_ACCESS_REVOKED: 'DOCUMENT_ACCESS_REVOKED',


  ACCESS_DENIED: 'ACCESS_DENIED',
});