export const PERMISSIONS = Object.freeze({
  USER_CREATE: 'USER_CREATE',
  USER_READ: 'USER_READ',
  USER_UPDATE: 'USER_UPDATE',
  USER_DEACTIVATE: 'USER_DEACTIVATE',

  ROLE_ASSIGN: 'ROLE_ASSIGN',

  DOCUMENT_CREATE: 'DOCUMENT_CREATE',
  DOCUMENT_VIEW: 'DOCUMENT_VIEW',
  DOCUMENT_DOWNLOAD: 'DOCUMENT_DOWNLOAD',
  DOCUMENT_UPDATE: 'DOCUMENT_UPDATE',
  DOCUMENT_DEACTIVATE: 'DOCUMENT_DEACTIVATE',
  DOCUMENT_ACCESS_MANAGE: 'DOCUMENT_ACCESS_MANAGE',

  AUDIT_READ: 'AUDIT_READ',

  DASHBOARD_READ: 'DASHBOARD_READ',
});